version: '2'

services:
  api:
    container_name: nest_api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/api
    environment:
      DB_HOST: database
      DB_PORT: 5432

  database:
    image: 'kartoza/postgis:latest'
    volumes:
      - ./data/postgre/db:/data/db
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
